#NEW VERSIONS WITH NO TRANSACTIONAL
#version: '3.8'
#services:
#  mongo:
#    image: mongo:latest
#    restart: always
#    container_name: blogrudb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: db1
#    volumes:
#      - ./data:/data/db
#      - ./data/log:/var/log/mongodb
#    ports:
#      - "27017:27017"


version: '2'

services:
  mongodb-dev-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/bitnami
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_USERNAME=user1
      - MONGODB_PASSWORD=pass1
      - MONGODB_DATABASE=db1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=rootpass1
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs1

